apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: vfbootcamp
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "rootuser"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "rootpass"
          volumeMounts:
            - name: mongodb
              mountPath: /data/db
      volumes:
        - name: mongodb
          persistentVolumeClaim:
            claimName: mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: vfbootcamp
  labels:
    app: mongodb
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongodb
